name: network_inspector
description: Http inspector / logger for Dio and Http package. This package would allow you to log every Http request, response, and error from Dio & Http.
version: 1.1.0
homepage: https://github.com/Meruya-Techhnology/network_inspector

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^4.0.6
  sqflite: ^2.2.6
  provider: ^6.0.5
  intl: ^0.17.0
  collection: any
  share_plus: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/json/
